format = """
$time\
$username\
$hostname\
$directory\
$git_branch\
$cmd_duration\
$line_break\
$character"""

add_newline = false

[character]
success_symbol = "[‚ûú](bold green)"
error_symbol = "[‚úó](bold red)"

[username]
style_user = "bold green"
style_root = "bold fg:#ff6188"
format = "[$user]($style)@"
show_always = true

[hostname]
style = "bold green"
format = "[$hostname]($style) "

[directory]
style = "bold fg:#ff6188"
truncation_length = 3
truncation_symbol = "‚Ä¶/"
read_only = "üîí"
read_only_style = "fg:#ff6188"
format = "[$path]($style)[$read_only]($read_only_style)|"

[git_branch]
symbol = "ÓÇ†"
style = "bold fg:#ff6188"
format = "[$symbol$branch]($style)| "

[git_status]
style = "fg:#ff6188"
format = "[$all_status$ahead_behind]($style) "

[time]
disabled = false
time_format = "%H:%M"
style = "bold green"
format = "|[$time]($style)|"

[cmd_duration]
min_time = 1000
style = "bold fg:#a9dc76"
format = "[‚è± $duration]($style) "

[python]
symbol = "Óúº "
style = "fg:#ab9df2"
format = "[$symbol$version]($style) "

[rust]
symbol = "Óû® "
style = "bold fg:#ff6188"
format = "[$symbol$version]($style) "

[c]
symbol = "Óòû "
style = "bold fg:#fc9867"
format = "[$symbol$version]($style) "

[cpp]
symbol = "Óòù "
style = "bold fg:#ab9df2"
format = "[$symbol$version]($style) "

[lua]
symbol = "Ó†¶ "
style = "bold fg:#7fdbca"
format = "[$symbol$version]($style) "

